# DS3000 Lesson 3

Sep 20, 2022

Admin
- Qwickly Attendance (cancelled, because class is virtual due to Professor Covid)
- Style Guide on Canvas
- Homework 1 due tonight by midnight
- Homework 2 posted, due next Tuesday by midnight
- Meta Senior Research Data Scientist Q\&A on Friday (and Lab 2)
    - Come up with a question to ask for +3 points extra credit on the Lab

Content
- numpy & arrays
- pandas
    - series
    - dataframe
- seaborn

# Why do we make such a fuss to represent data as arrays?
Its often a convenient analogy to consider a dataset as a big table.  A dataset describes the **features** of a collection of **samples**:
- each row represents a sample
    - e.g. a penguin
- each column represents a feature
    - e.g. how heavy the penguins are
- the intersection of a row and column contains the feature of the sample
    - e.g. how heavy a particular penguin is
    
<img src="https://imgur.com/orZWHly.png" width=300 />


In [1]:
# (we'll cover this code later, for now I just want us all to
# look at a dataset together)

import seaborn as sns

# data source: https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

Why represent data in 2d arrays?
- many datasets well encapsulated as a 2d array with 
    - different rows used for samples
    - different col used feature
- Arrays (matrices) are natural math objects in linear algebra, probability and statistics all of which underpin machine learning.

## Rows vs Columns
<img src="https://learnenglishfunway.com/wp-content/uploads/2021/07/Row-vs-Column.jpg" width=700 />

## **NumPy** (**Numerical Python**) Library
* First appeared in 2006 and is the **preferred Python array implementation**.
* High-performance, richly functional **_n_-dimensional array** type called **`ndarray`**. 
* **Written in C** and **up to 100 times faster than lists**.
* Critical in big-data processing, AI applications and much more. 
* According to `libraries.io`, **over 450 Python libraries depend on NumPy**. 
* Many popular data science libraries such as Pandas, SciPy (Scientific Python) and Keras (for deep learning) are built on or depend on NumPy. 

Big Question:
```
What is an array/matrix?  (and how is different than a list or list of lists?)
```

| Array                                 | List (Python: Dynamic Array)                         |
|---------------------------------------|------------------------------------------------------|
| Size is static (contiguous memory)    | Size can be modified quickly (non-contiguous memory) |
| Quick to compute (esp Linear Algebra) | Slower to compute (and clumsy looking code)          |
| contains 1 datatype (numeric)         | may contain many data types (need not be numeric)    |

### Initializing arrays:
- 1d from list / tuple
- 2d from list / tuple

In [2]:
import numpy as np

# x is a 1d array (3)
x = np.array((1, 2, 3))
x

array([1, 2, 3])

In [3]:
# y is a 2d array (2, 3)
y = np.array([[1, 2, 3],
              [4, 5, 6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

### Building some special matrices
- zeros
- ones
- full 
- identity


<img src="https://learnenglishfunway.com/wp-content/uploads/2021/07/Row-vs-Column.jpg" width=200 />

#### Convention: Rows First!
- we describe array shape as `(n_rows, n_cols)`
- we index into an array as `x[row_idx, col_idx]`

In [4]:
# shape = (n_rows, n_cols)
# shape = (height, width)
# .zeros gives an array of all zeros
z = np.zeros((5, 2)) # tall array
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
# .ones gives an array of all ones
one_array = np.ones((2, 5), dtype=int)
one_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
# can use .full to create an array of all fill_value
# np.full(shape=(2,5), fill_value=2)
two_array = np.full(shape=(2, 5), fill_value=2.0)
two_array

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [7]:
# identity matrix
# 1's on the diagonal, 0s elsewhere
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arrays which change: 
- `.arange()`
- `.linspace()`
- `.geomspace()`
- `.logspace()`

In [8]:
# note: not "arrange", but rather "(a)rray (range)"
# np.arange(start (inclusive), stop (exclusive), step)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# linearly spaced values np.linspace(start (inclusive), stop (inclusive), size)
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [10]:
# geom spaced values np.geomspace(start (inclusive), stop (inclusive), size)
np.geomspace(1, 27, 4)

array([ 1.,  3.,  9., 27.])

In [11]:
# log spaced value np.logspace(start_exp, stop_exp, size)
# start = 10^start_exp, stop = 10^stop_exp
np.logspace(0, 2, 3)

array([  1.,  10., 100.])

### Array Attributes
- shape
- size
- ndim

Numpy can build arrays out of many different number types (bool, int, float).  ([see also](https://numpy.org/doc/stable/user/basics.types.html#:~:text=There%20are%205%20basic%20numerical,point%20(float)%20and%20complex.&text=NumPy%20knows%20that%20int%20refers,int_%20%2C%20bool%20means%20np.))
- dtype
    - astype
- nbytes

In [12]:
x = np.array([[1, 2, 3],
              [4, 5, 6]]) 

In [13]:
# whether you see int32 or int64 depends on the bit size; it should not truly matter
x.dtype

dtype('int32')

In [14]:
# ndim is the (n)umber of (dim)ensions
x.ndim

2

In [15]:
# shape gives the values of the dimensions
x.shape

(2, 3)

In [16]:
# size is total number of elements
x.size

6

In [17]:
x.nbytes

24

In [18]:
# converting the type of an array can help lower the memory demands
# https://numpy.org/doc/stable/user/basics.types.html
x_low_mem = np.array([[1, 2, 3],
                      [4, 5, 6]], np.uint8)
x_low_mem.nbytes

6

## Manipulating array shape

### Diagonal

The diagonal of each array is shaded below, the unshaded elements are not on the diagonal of the matrix:

$$ \begin{bmatrix}
\blacksquare & \square & \square\\
\square & \blacksquare & \square\\
\square & \square & \blacksquare\\
\square & \square & \square\\
\end{bmatrix} 
\hspace{2cm}
\begin{bmatrix}
\blacksquare & \square & \square & \square & \square\\
\square & \blacksquare & \square& \square & \square\\
\square & \square & \blacksquare& \square & \square\end{bmatrix}
\hspace{2cm}
\begin{bmatrix}
\blacksquare & \square & \square\\
\square & \blacksquare & \square\\
\square & \square & \blacksquare
\end{bmatrix} 
$$

### Numpy methods
- transpose
- `.reshape()`
    - order of reshape (row or column first?)

In [19]:
x = np.array([[1, 2, 3],
              [4, 5, 6]]) 
x

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# transpose (.T): flip across the diagonal
y = x.T
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
# reshape allows us to change shape of matrix by defining the dimensions
x.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [22]:
# (new matrix must have same total number of elements)
# x.reshape((1, 8))

In [23]:
z = np.arange(0, 12)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
z.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# -1 may be used at most once in the shape argument; it is used to tell python to
# choose the value to ensure output array has same number of elements
z.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
# be mindful that -1 can be replaced by some integer to keep same number of elements in array
# but you need to make sure that the multiplication works!
# z.reshape((5, -1))

In [27]:
# we can fill the array across the rows first (order='C'), which is the default
z.reshape((3, 4), order='C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
# or down columns first (order='F')
z.reshape((3, 4), order='F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

## Array Indexing (slicing)

You can index arrays, everything we've previously shown about `start:stop:step` indexing works for arrays too!

In [29]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
x[5]

5

In [31]:
x[2:6]

array([2, 3, 4, 5])

In [32]:
x[-3:]

array([ 8,  9, 10])

In [33]:
x[:5]

array([0, 1, 2, 3, 4])

A two dimensional array requires two indices to get a value: `x[row_idx, col_idx]`

(Just like our convention for rows first in shape, the row index comes first as we index into the array)

In [34]:
x = np.arange(20).reshape((4, 5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
# row_idx=1 (second row since python starts counting at 0)
# col_idx=2 (third row since python starts counting at 0)
x[1, 2]

7

In [36]:
# we can start:stop:step slice either index

# get a slice of rows and a constant column
x[0:2, 2]

array([2, 7])

In [37]:
# get a slice of columns and a constant row
x[2, 0:2]

array([10, 11])

## Super useful slice syntax on arrays:
(so useful it deserves its own title)

In [38]:
# by default, the slice indexing chooses start:stop to give the entire object
x = np.array([1, 2, 3])
x[:]

array([1, 2, 3])

In [39]:
# we can use this to get an entire rows or columns as needed
x = np.arange(20).reshape((4, 5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
# get the first column
x[:, 0]

array([ 0,  5, 10, 15])

In [41]:
# get the second row
x[1, :]

array([5, 6, 7, 8, 9])

In [42]:
# get the last two columns
x[:, -2:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

### Computing stats on an array
- `.sum()`
- `.min()`
- `.max()`
- `.mean()`
- `.std()`
    - standard deviation
- `.var()`
    - variance
- `.argmin()`
    - index of item which is smallest
- `.argmax()`
    - index of item which is largest

In [43]:
x = np.array([4, 3, 5, 4])
x

array([4, 3, 5, 4])

In [44]:
# get index of smallest item
# (smallest item, 3, is at index 1)
x.argmin()

1

In [45]:
y = np.arange(100, 112).reshape((3, 4))
y

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [46]:
y.sum(), y.min(), y.max(), y.mean(), y.std(), y.var()

(1266, 100, 111, 105.5, 3.452052529534663, 11.916666666666666)

In [47]:
# axis: which of the shape parameters should I operate on? 
# shape = (shape0, shape1)

# axis=0 averages across different rows to give the column average
y.mean(axis=0)

array([104., 105., 106., 107.])

In [48]:
# axis=1 averages across different columns to give the row average
y.mean(axis=1)

array([101.5, 105.5, 109.5])

In [49]:
# axis is an accepted keyword of all methods listed above
y.min(axis=1)

array([100, 104, 108])

In [50]:
y.min(axis=0)

array([100, 101, 102, 103])

## Why are we doing this again?

<img src="https://imgur.com/orZWHly.png" width=300 />

In [51]:
import seaborn as sns

# data source: https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

## Array Operations: 
- array and a scalar: 
    - apply operation to every element of array
- array and array: 
    - apply operation to corresponding elements of arrays (requires shape or [special](https://numpy.org/doc/stable/user/basics.broadcasting.html) structure)


In [52]:
y1 = np.arange(12).reshape((3, 4))
y

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [53]:
y1 + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [54]:
y1 * 10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [55]:
y1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [56]:
# array and array arithmetic
y2 = np.arange(100, 112).reshape((3, 4))
y2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [57]:
# array and array arithmetic applies operation to corresponding items in arrays
y1 + y2

array([[100, 102, 104, 106],
       [108, 110, 112, 114],
       [116, 118, 120, 122]])

In [58]:
y1 * y2

array([[   0,  101,  204,  309],
       [ 416,  525,  636,  749],
       [ 864,  981, 1100, 1221]])

In [59]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
# (++) adding a constant row (x) to all rows of a matrix (y1)
# more details here: https://numpy.org/doc/stable/user/basics.broadcasting.html
x = np.array([1000, 2000, 3000, 4000])
y1 + x

array([[1000, 2001, 3002, 4003],
       [1004, 2005, 3006, 4007],
       [1008, 2009, 3010, 4011]])

# Pandas

Pandas is a python module which stores data.  

### If we already have `np.array()`, why do we need pandas?
- pandas supports non numeric data (strings for categorical data, for example)
- pandas supports reading / storing data from more formats
    - csv (spreadsheets)
- pandas more elegantly deals with missing data
- pandas handles indexing woes

You could do almost everything pandas does with numpy arrays ... but it would be much more difficult to accomplish.

### Pandas has two essential objects:
- **dataframe**
    - 2 dimensional data structure
    - you've already seen one today!  (we replicate below)
- **series (vectors)**
    - 1 dimensional data structure, each item associated with some index
    - you could store the weight of all the penguins as a series 
        - (all samples of one feature)
    - you could store the weight, bill size, sex, island, etc for a single penguin as a series
        - (all features for one sample)

In [61]:
import seaborn as sns

# df stands for dataframe.  df_penguin is a dataframe of penguin data
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [62]:
# the table above is a dataframe
type(df_penguin)

pandas.core.frame.DataFrame

## Pandas Series
### building:
- building: default index
- building: custom index
- building: from a dict

In [63]:
# each row, or column is a series object
# this represents first row of dataframe
penguin0_series = df_penguin.iloc[0, :]
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
Name: 0, dtype: object

Pandas series contain a sequence of labelled data elements:
- penguin0's `species` is `Adelie`
- penguin0's `island` is `Torgersen`
- penguin0's `bill_length_mm` is `39.1` ...
- penguin0's `<index-name>` is `<corresponding-value>`

A series is quite similar to a dictionary ...

In [64]:
penguin0_dict = {'species': 'Adelie',
 'island': 'Torgersen',
 'bill_length_mm': 39.1,
 'bill_depth_mm': 18.7,
 'flipper_length_mm': 181.0,
 'body_mass_g': 3750.0,
 'sex': 'Male'}

In [65]:
import pandas as pd

# build a series from dict
penguin0_series = pd.Series(penguin0_dict)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [66]:
# you can also pass two corresponding lists / tuples
index = ['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex']
values = ['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male']

penguin0_series = pd.Series(values, index=index)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [67]:
# sometimes your data has no meaningful index
# pandas will default to indexing things with integers
ice_cream_flavors = 'vanilla', 'chocolate', 'cherry garcia', 'oatmeal'
pd.Series(ice_cream_flavors)

0          vanilla
1        chocolate
2    cherry garcia
3          oatmeal
dtype: object

In [68]:
# you can access values via .values
penguin0_series.values

array(['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male'],
      dtype=object)

In [69]:
# you can access index via .index
penguin0_series.index

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

### accessing / changing data
- accessing custom index:
    - by name: `series.loc[name]`
    - by position: `series.iloc[idx]`
- iterating: keys, items, iteritems (much like dict)
- deleting an entry

In [70]:
dict_fav_num = {'eric':  17, 'qi': 7, 'lynne': 3, 'tamrat': 1}
series_fav_num = pd.Series(dict_fav_num)
series_fav_num

eric      17
qi         7
lynne      3
tamrat     1
dtype: int64

In [71]:
# lookup value associated with index='eric'
series_fav_num['eric']

17

In [72]:
# another way to lookup value associated with index='eric'
series_fav_num.loc['eric']

17

In [73]:
# return the value in position 2 (the third position, from top)
# two ways
series_fav_num[2]
# series_fav_num.iloc[2]

3

In [74]:
# each of these access methods can also set the value
series_fav_num.iloc[2] = 1000
series_fav_num

eric        17
qi           7
lynne     1000
tamrat       1
dtype: int64

In [75]:
for idx in series_fav_num.index:
    print(idx)

eric
qi
lynne
tamrat


In [76]:
# check membership of item in index
'eric' in series_fav_num.index

True

In [77]:
'alice' in series_fav_num.index

False

In [78]:
# iterating through values
for val in series_fav_num.values:
    print(val)

17
7
1000
1


In [79]:
# iterating through index (just a like dict!)
# .keys() produces same thing as .index
for key in series_fav_num.keys():
    print(key)

eric
qi
lynne
tamrat


In [80]:
# iterating through index, value pairs (just like dict!)
for key, val in series_fav_num.items():
    print(key, val)

eric 17
qi 7
lynne 1000
tamrat 1


In [81]:
# removing a pair by its corresponding index (just like dict!)
del series_fav_num['eric']

In [82]:
series_fav_num

qi           7
lynne     1000
tamrat       1
dtype: int64

### Describing a `pd.Series`

Just like numpy arrays:
- `Series.argmin()`
    - which index has smallest value
    - pandas gives the row number, not the index
- `Series.argmax()`
    - which index has largest value
    - pandas gives the row number, not the index
- `Series.mean()`
- `Series.min()`
- `Series.max()`
- `Series.std()`
- `Series.var()`

New to pandas:
- `Series.count()`
    - number of item pairs in series
- `Series.describe()`
    - summary statistics

In [83]:
# number of entries (rows)
series_fav_num.count()

3

In [84]:
# other descriptors/summary statistics
series_fav_num.describe()

count       3.000000
mean      336.000000
std       575.048694
min         1.000000
25%         4.000000
50%         7.000000
75%       503.500000
max      1000.000000
dtype: float64

## Pandas: DataFrame

Remember:
- `Series`:  1d data object
- `DataFrame`: 2d data object

`DataFrame`s represent two-dimensional data, for example, grades:

|           | Quiz 0 | Quiz 1 | Quiz 2 |
|-----------|--------|--------|--------|
| Student 0 | 80     | 90     | 50     |
| Student 1 | 87     | 92     | 80     |

Each column or row above could be considered a `Series` object (as we'll see later, we can indeed extract a single row or column of a dataframe as a `Series` object).

In [85]:
import pandas as pd
import numpy as np

quiz_array = np.array([[80, 90, 50],
                 [87, 92, 80]])

df_quiz = pd.DataFrame(quiz_array, 
                       columns=('quiz0', 'quiz1', 'quiz2'), 
                       index=('student0', 'student1'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [86]:
# we construct a dataframe as a dictionary
# keys of the dictionary are columns of dataframe
# values are lists (or tuples) of the values in each column
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
pd.DataFrame(quiz_dict, index=('student0', 'student1'))

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [87]:
# another way to construct, this time the transpose
quiz_dict2 = {'student0': [80, 90, 50],
             'student1': [87, 92, 80]}
pd.DataFrame(quiz_dict2, index=('quiz0', 'quiz1', 'quiz2'))

student0  student1
quiz0        80        87
quiz1        90        92
quiz2        50        80

In [88]:
# could also use .transpose() or even .T
df_quiz.transpose()
# df_quiz.T

student0  student1
quiz0        80        87
quiz1        90        92
quiz2        50        80

In [89]:
# we can also add the column or index names after creation
df_quiz = pd.DataFrame(quiz_array)
df_quiz

0   1   2
0  80  90  50
1  87  92  80

In [90]:
df_quiz.columns = ['quiz0', 'quiz1', 'quiz2']
df_quiz.index = ('student0', 'student1')
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

### Describing a `pd.DataFrame`

Similar to Series (for now), but with a couple differences:
- `DataFrame.iloc[].argmin()` or `DataFrame.loc[].argmin()` 
    - note that this does not work on the DataFrame itself, but on specified series/rows
    - which index has smallest value
    - pandas gives the row number, not the index
- `DataFrame.iloc[].argmax()` or `DataFrame.loc[].argmax()`
    - note that this does not work on the DataFrame itself, but on specified series/rows
    - which index has largest value
    - pandas gives the row number, not the index
- `DataFrame.mean()`
- `DataFrame.min()`
- `DataFrame.max()`
- `DataFrame.std()`
- `DataFrame.var()`

New to pandas:
- `DataFrame.count()`
    - number of item pairs in series
- `DataFrame.describe()`
    - summary statistics

In [91]:
# by default, each method applies operation to entire column of data
# note that there may be some complaining from python if not all the columns are numeric
df_quiz.mean()

quiz0    83.5
quiz1    91.0
quiz2    65.0
dtype: float64

In [92]:
# we can also pass axis parameter to specify if operation should be applied to row or column
# !remember!
# axis=0 -> apply operation across all rows (returns operation per col)
# axis=1 -> apply operation across all cols (returns operation per row)
df_quiz.mean(axis=1)

student0    73.333333
student1    86.333333
dtype: float64

In [93]:
# describe only works on columns
df_quiz.describe()

quiz0      quiz1      quiz2
count   2.000000   2.000000   2.000000
mean   83.500000  91.000000  65.000000
std     4.949747   1.414214  21.213203
min    80.000000  90.000000  50.000000
25%    81.750000  90.500000  57.500000
50%    83.500000  91.000000  65.000000
75%    85.250000  91.500000  72.500000
max    87.000000  92.000000  80.000000

## Indexing / Accessing a DataFrame
- indexing: 
    - `.loc[]` indexing by name of row or column
    - `.iloc[]` indexing by position integer (0, 1, 2, 3, 4 ...)
    & slicing & subsets
- using `:` to get full rows or columns
- single cell's contents: `at`, `iat` & slicing

In [94]:
# indexing data by "name"
# remember: rows first, then columns ... 
# 1st entry describes which row ('student0')
# 2nd entry describes which col ('quiz0')

df_quiz.loc['student0', 'quiz0']

80

In [95]:
# index data by position
# 1st entry describes which row.  0 -> the 1st (topmost) row
# 2nd entry describes which col.  2 -> the 3rd (from the left) col
df_quiz.iloc[0, 2]

50

In [96]:
# you can use same slicing syntaxes on both .loc and .iloc
# 1st row, last col
df_quiz.iloc[0, -1]

50

In [97]:
# all rows, only the second col
df_quiz.iloc[:, 1]

student0    90
student1    92
Name: quiz1, dtype: int32

In [98]:
# all rows, only quiz0
df_quiz.loc[:, 'quiz0']

student0    80
student1    87
Name: quiz0, dtype: int32

In [99]:
# slicing with named cols and rows
# you can get a range, by name of row/col
# note: this includes both start and stop columns
df_quiz.loc['student0', 'quiz0':'quiz2' ]

quiz0    80
quiz1    90
quiz2    50
Name: student0, dtype: int32

In [100]:
# watch out:
# when you get ranges indexed by position: include start idx, exclude stop idx)
df_quiz.iloc[0, 0:2 ]

quiz0    80
quiz1    90
Name: student0, dtype: int32

In [101]:
# if you access directly into dataframe, it will assume you're looking for a column
# (below is equivilent to df_quiz.loc[:, 'quiz0'])
df_quiz['quiz0']

student0    80
student1    87
Name: quiz0, dtype: int32

## Modifying a DataFrame
- updating values: single cell
- adding a new column
- `pd.DataFrame.append()`
    - adds a single row to a dataframe
    - deprecated, but works for now. will eventually be replaced with `pd.DataFrame.concat()`

In [102]:
# setting single entry in dataframe
df_quiz.loc['student0', 'quiz1'] = 123
df_quiz

quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [103]:
# adding a new column (which student got which grade?)
# notice data frames can include columns of multiple types!
df_quiz['overall grade'] = 'a', 'b' 
df_quiz

quiz0  quiz1  quiz2 overall grade
student0     80    123     50             a
student1     87     92     80             b

In [104]:
# delete a column
del df_quiz['overall grade']
df_quiz

quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [105]:
# adding a column (next 2 cells) more error robust way of handling indexing
# by explicitly labelling the index we're sure to match more explicitly
s_overgrade = pd.Series({'student1': 'b-',
                         'student0': 'a+',
                        'student2': 'f (no quizzes taken)'})
s_overgrade

student1                      b-
student0                      a+
student2    f (no quizzes taken)
dtype: object

In [106]:
# notice how pandas helps us out in aligning our new column with proper row
# (and avoids including student2)
df_quiz['overall grade'] = s_overgrade
df_quiz

quiz0  quiz1  quiz2 overall grade
student0     80    123     50            a+
student1     87     92     80            b-

In [107]:
# how to 'drop' a row (returns a dataframe with row removed)
df_quiz_short = df_quiz.drop('student0')
df_quiz_short

quiz0  quiz1  quiz2 overall grade
student1     87     92     80            b-

In [108]:
# rebuild df_quiz
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [109]:
# notice: name of series ends up on index of dataframe
# notice: order of items in series doesnt matter, they're aligned by index
s_student3 = pd.Series({'quiz1': 90,
                        'quiz2': 100,
                        'quiz0': 95},
                      name='student3')
s_student3

quiz1     90
quiz2    100
quiz0     95
Name: student3, dtype: int64

In [110]:
# add new row to dataframe
# NOTE: .append() will eventually be replaced with .concat()
df_quiz.append(s_student3)

C:\Users\Gerber\AppData\Local\Temp\ipykernel_14204\1159393492.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_quiz.append(s_student3)


quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student3     95     90    100

In [111]:
# also notice: .append() returns a copy of df_quiz, it isn't modified above
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

### Operating on DataFrame & Series Objects

Your operators do what you'd expect them to:

In [112]:
df_quiz * 1000

quiz0  quiz1  quiz2
student0  80000  90000  50000
student1  87000  92000  80000

In [113]:
# we can also use comparison operators (super helpful, see boolean indexing next)
df_quiz >= 85

quiz0  quiz1  quiz2
student0  False   True  False
student1   True   True  False

### Boolean Indexing into DataFrame

Sometimes we want to grab only the rows or columns which meet a particular condition.

"Get all students whose grade was higher than 85 on quiz 1"

In [114]:
quiz_dict = {'quiz0': [80, 87, 60, 30],
            'quiz1': [90, 92, 60, 23],
            'quiz2': [50, 80, 70, 64]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1', 'student2', 'student3'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student2     60     60     70
student3     30     23     64

In [115]:
# quiz 1 is a series object which contains every index's quiz 1 grade
s_quiz2 = df_quiz.loc[:, 'quiz2']
s_quiz2

student0    50
student1    80
student2    70
student3    64
Name: quiz2, dtype: int64

In [116]:
# boolean indexing: using a boolean series as index returns only those entries which are True
# notice that since student2 & student3's quiz1 grade wasn't > 80 they aren't included below
df_quiz.loc[s_quiz2 >= 70, :]

quiz0  quiz1  quiz2
student1     87     92     80
student2     60     60     70

In [117]:
# we can build more complex conditions using 
# & (and operator)
# | (or operator)

# all students who got at least an 80 on quiz1 but didn't score higher than 90 on quiz2
s_bool = (df_quiz.loc[:, 'quiz1'] > 80) & (df_quiz.loc[:, 'quiz2']  < 75)
s_bool

student0     True
student1    False
student2    False
student3    False
dtype: bool

In [118]:
df_quiz.loc[s_bool, :]

quiz0  quiz1  quiz2
student0     80     90     50

# Loading Data into Pandas

Data comes from many places:
- Web Scraping
- Application Program Interface (API)
- SQL
- local file:
    - csv
    - JSON
    - fixed width tables (HTML)
    
### Pandas functions which load data
| Mode | Description
| ------ | :------
| **`read_csv`** | Load comma seperated values data from a file or URL (other delimeters too!)
| **`read_xlsx`** | Read data in xls format (Mircosoft Excel)
| **`read-fwf`** | Read data in fixed-width column format (i.e., no delimiters such as tab-separated txt files)
| **`read_clipboard`** | Version of read_csv that reads data from the clipboard; useful for converting tables from web pages
| **`read_html`** | Read all tables contained in the given HTML document.
| **`read_json`** | Read data from a JSON (JavaScript Object Notation) string representation

## Reading CSV into Pandas
- read_csv
- index_col
- header

In [119]:
# note: file must be in same folder as jupyter notebook
pd.read_csv('cleaner_gtky.csv')

fake_student_id      time_stamp      class co_op  prog_exp python_exp  \
0              1380  09-09-22 15:37  Sophomore    No         9     Python   
1              3926  09-09-22 16:01  Sophomore    No         7     Python   
2              2394  09-09-22 14:19     Junior   Yes         7     Python   
3              4827  09-09-22 16:07     Junior    No         7     Python   
4              9977  09-09-22 16:06  Sophomore    No         5     Python   
..              ...             ...        ...   ...       ...        ...   
92             3775  09-09-22 15:50     Junior   Yes         8     Python   
93             1562  09-09-22 16:06  Sophomore    No         7       Java   
94             9610  09-09-22 14:13     Senior   Yes        10     Python   
95             2120  09-09-22 13:46     Junior   Yes         2       Java   
96             6664  09-09-22 13:43  Sophomore    No        10     Python   

   java_exp r_exp c_exp  age_months  ideal_start_salary_thousands  
0       NaN   NaN   NaN       234.0                          60.0  
1       NaN   NaN   NaN       233.0                         100.0  
2      Java   NaN   NaN       252.0                          70.0  
3      Java   NaN   NaN       243.0                          60.0  
4       NaN     R   NaN       231.0                          90.0  
..      ...   ...   ...         ...                           ...  
92      NaN     R   NaN       262.0                         100.0  
93      NaN   NaN   NaN       230.0                          73.0  
94     Java   NaN   NaN       264.0                         100.0  
95      NaN   NaN   NaN       246.0                         100.0  
96     Java   NaN   NaN       238.0                          75.0  

[97 rows x 11 columns]

In [120]:
# how to specify index col (make sure this is uniquely identifiable!)
pd.read_csv('cleaner_gtky.csv', index_col='fake_student_id')

time_stamp      class co_op  prog_exp python_exp  \
fake_student_id                                                         
1380             09-09-22 15:37  Sophomore    No         9     Python   
3926             09-09-22 16:01  Sophomore    No         7     Python   
2394             09-09-22 14:19     Junior   Yes         7     Python   
4827             09-09-22 16:07     Junior    No         7     Python   
9977             09-09-22 16:06  Sophomore    No         5     Python   
...                         ...        ...   ...       ...        ...   
3775             09-09-22 15:50     Junior   Yes         8     Python   
1562             09-09-22 16:06  Sophomore    No         7       Java   
9610             09-09-22 14:13     Senior   Yes        10     Python   
2120             09-09-22 13:46     Junior   Yes         2       Java   
6664             09-09-22 13:43  Sophomore    No        10     Python   

                java_exp r_exp c_exp  age_months  ideal_start_salary_thousands  
fake_student_id                                                                 
1380                 NaN   NaN   NaN       234.0                          60.0  
3926                 NaN   NaN   NaN       233.0                         100.0  
2394                Java   NaN   NaN       252.0                          70.0  
4827                Java   NaN   NaN       243.0                          60.0  
9977                 NaN     R   NaN       231.0                          90.0  
...                  ...   ...   ...         ...                           ...  
3775                 NaN     R   NaN       262.0                         100.0  
1562                 NaN   NaN   NaN       230.0                          73.0  
9610                Java   NaN   NaN       264.0                         100.0  
2120                 NaN   NaN   NaN       246.0                         100.0  
6664                Java   NaN   NaN       238.0                          75.0  

[97 rows x 10 columns]

In [121]:
# look at the first few rows (header)
gtky = pd.read_csv('cleaner_gtky.csv', index_col='fake_student_id')
gtky.head()

time_stamp      class co_op  prog_exp python_exp  \
fake_student_id                                                         
1380             09-09-22 15:37  Sophomore    No         9     Python   
3926             09-09-22 16:01  Sophomore    No         7     Python   
2394             09-09-22 14:19     Junior   Yes         7     Python   
4827             09-09-22 16:07     Junior    No         7     Python   
9977             09-09-22 16:06  Sophomore    No         5     Python   

                java_exp r_exp c_exp  age_months  ideal_start_salary_thousands  
fake_student_id                                                                 
1380                 NaN   NaN   NaN       234.0                          60.0  
3926                 NaN   NaN   NaN       233.0                         100.0  
2394                Java   NaN   NaN       252.0                          70.0  
4827                Java   NaN   NaN       243.0                          60.0  
9977                 NaN     R   NaN       231.0                          90.0

In [122]:
# or the last few (tail)
gtky.tail()

time_stamp      class co_op  prog_exp python_exp  \
fake_student_id                                                         
3775             09-09-22 15:50     Junior   Yes         8     Python   
1562             09-09-22 16:06  Sophomore    No         7       Java   
9610             09-09-22 14:13     Senior   Yes        10     Python   
2120             09-09-22 13:46     Junior   Yes         2       Java   
6664             09-09-22 13:43  Sophomore    No        10     Python   

                java_exp r_exp c_exp  age_months  ideal_start_salary_thousands  
fake_student_id                                                                 
3775                 NaN     R   NaN       262.0                         100.0  
1562                 NaN   NaN   NaN       230.0                          73.0  
9610                Java   NaN   NaN       264.0                         100.0  
2120                 NaN   NaN   NaN       246.0                         100.0  
6664                Java   NaN   NaN       238.0                          75.0

In [128]:
# look at stats for the different classes
class_gtky = gtky.groupby("class")
class_gtky.describe()

prog_exp                                               age_months  \
              count    mean       std  min   25%  50%   75%   max      count   
class                                                                          
Faculty         1.0  8.0000       NaN  8.0  8.00  8.0  8.00   8.0        1.0   
Fifth year      6.0  7.0000  3.098387  3.0  4.50  7.5  9.75  10.0        5.0   
Junior         16.0  7.4375  2.393568  2.0  6.50  8.0  9.25  10.0       15.0   
Senior         24.0  7.5000  2.146787  3.0  5.75  8.0  9.25  10.0       24.0   
Sophomore      50.0  7.8200  1.560874  5.0  7.00  8.0  9.00  10.0       50.0   

                       ...                ideal_start_salary_thousands  \
                 mean  ...     75%    max                        count   
class                  ...                                               
Faculty     381.00000  ...  381.00  381.0                          1.0   
Fifth year  263.20000  ...  270.00  276.0                          4.0   
Junior      247.60000  ...  249.50  262.0                         16.0   
Senior      260.71875  ...  264.25  281.0                         19.0   
Sophomore   233.56000  ...  236.00  245.0                         48.0   

                                                                      
                  mean        std    min    25%    50%    75%    max  
class                                                                 
Faculty     100.000000        NaN  100.0  100.0  100.0  100.0  100.0  
Fifth year   90.000000  25.819889   60.0   75.0   90.0  105.0  120.0  
Junior       96.250000  39.602188   40.0   70.0  100.0  100.0  200.0  
Senior       87.510526  13.334871   50.7   80.0   90.0  100.0  100.0  
Sophomore    99.916667  63.667966   58.0   80.0   90.0  100.0  500.0  

[5 rows x 24 columns]

## Saving a DataFrame as a csv
- .to_csv()
- index=False
- header=False
- appending to csv (mode='a', header=None)

In [123]:
# doesn't save index into first column of csv
gtky.to_csv('gtky_copy.csv', index=False)

In [124]:
# doesn't save header into first row of csv
gtky.to_csv('gtky_copy_no_head.csv', header=False)

In [125]:
# why would you want to not save the header?
# you could append to an existing csv with mode = 'a'

gtky.to_csv('gtky_copy2.csv', index=False)
for _ in range(10):
    gtky.to_csv('gtky_copy2.csv', header=False, mode='a')

The example above seems a bit contrived, but imagine you have a web-scraping job which goes to some financial web page every hour and scrapes it to get some new data (more to come on this later).  You could just add the new data as a few new rows to your existing dataset with the syntax shown above.