# DS 3000 HW 2 $\color{red}{\text{SOLUTIONS}}$

Due: Tuesday Sep 27 @ 11:59 PM EST

### Submission Instructions
Submit this `ipynb` file to Gradescope ([1:35 Section](https://www.gradescope.com/courses/431947) [3:25 Section](https://www.gradescope.com/courses/431864)) (this can also be done via the assignment on Canvas).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to gradescope.

### Tips for success
- Start early
- Make use of Piazza ([1:35 Section](https://piazza.com/class/l7dkfe3cgz21ul) [3:25 Section](https://piazza.com/class/l7dkey4g6m71e5)) (also accessable through Canvas)
- Make use of [Office Hours](https://docs.google.com/spreadsheets/d/1SMacPh9lhRvjHI1VCJfBbNGSga3RTYKzSsfRWEWqWQI/edit?usp=sharing)
- Remember to use cells and headings to make the notebook easy to read (if a grader cannot find the answer to a problem, you will receive no points for it)
    - Remember that documentation/style is important (See the Style Guide on Canvas!)
- Under no circumstances may one student view or share their ungraded homework or quiz with another student [(see also)](http://www.northeastern.edu/osccr/academic-integrity), though you are welcome to **talk about** (not show each other) the problems.

# Part 1: Arrays

## Part 1.1: (10 points: 5 pts each)

Create the following two arrays using the NumPy library. Call the first array `array_a` and the second array `array_b`:

$$\text{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & 43 & 2
\end{bmatrix}$$

$$\text{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$



$\color{red}{\text{Solution:}}$

In [1]:
# make sure to import numpy library
import numpy as np

# creating array_a manually with tuples
array_a = np.array([[3, 8, -2, 3],
              [.5, -1, 6, 4],
              [-5, 7, 43, 2]])

# creating array_b taking advantage of .linspace and .reshape
array_b = np.linspace(42, -14, 15).reshape(5, 3)

In [2]:
array_a

array([[ 3. ,  8. , -2. ,  3. ],
       [ 0.5, -1. ,  6. ,  4. ],
       [-5. ,  7. , 43. ,  2. ]])

In [3]:
array_b

array([[ 42.,  38.,  34.],
       [ 30.,  26.,  22.],
       [ 18.,  14.,  10.],
       [  6.,   2.,  -2.],
       [ -6., -10., -14.]])

## Part 1.2: (15 points: 5 pts each)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b`, then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

$\color{red}{\text{Solution:}}$

In [4]:
# printing all array_a attributes
print(array_a.shape)
print(array_a.size)
print(array_a.ndim)
print(array_a.nbytes)

(3, 4)
12
2
96


In [5]:
# printing all array_b attributes
print(array_b.shape)
print(array_b.size)
print(array_b.ndim)
print(array_b.nbytes)

(5, 3)
15
2
120


In [6]:
# transposing both
t_array_a = array_a.T
t_array_b = array_b.T

In [7]:
# trying to add array_a to t_array_b
# array_a + t_array_b

In [8]:
# removing last column of t_array_b (multiple ways to do this)
t_array_b = array_b.T[:,0:4]

# adding again
array_a + t_array_b

array([[45. , 38. , 16. ,  9. ],
       [38.5, 25. , 20. ,  6. ],
       [29. , 29. , 53. ,  0. ]])

When we first tried to add them, we received an error that they could not be broadcast together because of their different dimensions. By removing the last column of `t_array_b`, we made sure they were the same dimension and could be added together.

# Part 2: Bike Data

## Part 2.1: DataFrame Construction (10 points)
Recreate the following table of bicycle race data as a dataframe (do not write a csv and read it in to accomplish this; use pandas).  Use the `Bike ID` as the index column and save the resulting dataframe as a csv (you need not submit this csv, but be sure to include the `DataFrame.to_csv()` command in your submission).

| Bike ID | Rider ID | Make      | Color      | Bike Type  | Weight (g) | Time Trial 1 (s) | Time Trial 2 (s) |
|---------|----------|-----------|------------|------------|------------|------------------|------------------|
| 037     | 3        | Bianchi   | Celeste    | Road       | 8200       | 450              | 205              |
| 379     | 1        | Duratec   | \<no paint>| Cyclocross | 9500       | 510              | 222              |
| 398     | 7        | Trek      | Red        | Road       | 9000       | 432              | 211              |
| 37B     | 3        | Trek      | Black      | Mountain   | 13607      | 561              | 301              |
| BRG     | 7        | Canondale | Black      | Mountain   | 15005      | 524              | 299              |

$\color{red}{\text{Solution:}}$

In [9]:
# import pandas
import pandas as pd

# creating the dictionary (may also create individual series)
bike_dict = {'Rider ID': [3, 1, 7, 3, 7],
            'Make': ['Bianchi', 'Duratec', 'Trek', 'Trek', 'Canondale'],
            'Color': ['Celeste', '<no paint>', 'Red', 'Black', 'Black'],
            'Bike Type': ['Road', 'Cyclocross', 'Road', 'Mountain', 'Mountain'],
            'Weight (g)': [8200, 9500, 9000, 13607, 15005],
            'Time Trial 1 (s)': [450, 510, 432, 561, 524],
            'Time Trial 2 (s)': [205, 222, 211, 301, 299]}

df_bike = pd.DataFrame(bike_dict, index=['037',  '379',  '398',  '37B', 'BRG'])

# save as .csv
df_bike.to_csv('df_bike.csv')

df_bike

Rider ID       Make       Color   Bike Type  Weight (g)  \
037         3    Bianchi     Celeste        Road        8200   
379         1    Duratec  <no paint>  Cyclocross        9500   
398         7       Trek         Red        Road        9000   
37B         3       Trek       Black    Mountain       13607   
BRG         7  Canondale       Black    Mountain       15005   

     Time Trial 1 (s)  Time Trial 2 (s)  
037               450               205  
379               510               222  
398               432               211  
37B               561               301  
BRG               524               299

# Part 2.2: Manipulating DataFrames (30 points: 10 pts each)
For each of the questions below:
- Provide a few (1 to 3) code cells which construct a series or dataframe object which is sufficient to answer each question
    - one shouldn't have to look at the full dataframe or otherwise as reference
        - we practice this way as real datasets are too big for this to be easily done!
- Provide a markdown cell which contains a one sentence response to each question
    - In effect, you're interpretting the code cell(s) so one who knows no python can understand how your code answers the question

### Questions:
1. Which `Bike ID` has the greatest weight?
1. Which `Bike ID` has the fastest average time trial?
1. What is the average weight of each bike, per `Bike Type `?  
    - Hint: `groupby()` and/or `.unique()` might be helpful

Note that:
- each time trial records the time taken to complete a given track under similar conditions. 
- some riders (3 and 7) completed the time trials on two distinct bikes, the data is stored in distinct rows

$\color{red}{\text{Solution:}}$

In [10]:
# one way to find the greatest weight
df_bike.iloc[:,4].argmax()

4

The `Bike ID` with the greatest weight is `BRG`.

In [11]:
# one way to find the fastest averate time
df_bike.iloc[:,5:7].mean(axis=1)

037    327.5
379    366.0
398    321.5
37B    431.0
BRG    411.5
dtype: float64

The `Bike ID` with the fastest average time trial is `398` (remember that faster means lower time).

In [12]:
# one way to find the average weight of each bike per bike type
# look at stats for the different classes
type_bike = df_bike.groupby("Bike Type")
type_bike.mean()

Rider ID  Weight (g)  Time Trial 1 (s)  Time Trial 2 (s)
Bike Type                                                           
Cyclocross       1.0      9500.0             510.0             222.0
Mountain         5.0     14306.0             542.5             300.0
Road             5.0      8600.0             441.0             208.0

We see that Mountain Bikes are heaviest, then Cyclocross, then Road.

# Part 3: Pokémon Data

## Part 3.1: Reading in Data (5 points)

On Canvas is the `pokedata.csv` file. Read this data set in, using the `Pokedex` as the index column, and print the first few rows of the data.

$\color{red}{\text{Solution:}}$

In [13]:
# reading in the data, with appropriate index column, and printing the head
pokedata = pd.read_csv('pokedata.csv', index_col='Pokedex')
pokedata.head()

Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
1         Bulbasaur    Grass        Poison      24    25.2      45         45   
2           Ivysaur    Grass        Poison      39    28.7      60         60   
3          Venusaur    Grass        Poison      79   220.5      80         80   
4        Charmander     Fire           NaN      24    18.7      39         65   
5        Charmeleon     Fire           NaN      43    41.9      58         80   

         Attack  Defense  
Pokedex                   
1            49       49  
2            62       63  
3            82       83  
4            52       43  
5            64       58

## Part 3.2: More Manipulation (30 points: 10 pts each)

1. Add a new column to the data set that calculates the BMI of the Pokémon. The formula for BMI using Imperial Units (such as these data contain) is = $703 \times \frac{Weight}{Height^2}$. Print the first few rows.
    - Find out which Pokémon have (a) the highest BMI and (b) the lowest BMI.
1. Create a subset of the Pokémon Data that you created in (1) which (a) includes only Pokémon that have `BaseSpeed >= 60` and (b) excludes all Pokémon with `MainType == Fire`. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the Pokémon Data from the data from (1). Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

$\color{red}{\text{Solution:}}$

In [14]:
# creating BMI and then printing the head
pokedata['BMI'] = 703 * (pokedata['Weight'] / (pokedata['Height'] ** 2))
pokedata.head()

Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
1         Bulbasaur    Grass        Poison      24    25.2      45         45   
2           Ivysaur    Grass        Poison      39    28.7      60         60   
3          Venusaur    Grass        Poison      79   220.5      80         80   
4        Charmander     Fire           NaN      24    18.7      39         65   
5        Charmeleon     Fire           NaN      43    41.9      58         80   

         Attack  Defense        BMI  
Pokedex                              
1            49       49  30.756250  
2            62       63  13.265023  
3            82       83  24.837606  
4            52       43  22.823090  
5            64       58  15.930611

In [15]:
# identifying highest and lowest BMI pokemon (may be a few ways to do this)
print(pokedata['Pokemon'][pokedata.iloc[:,9].argmax()])
print(pokedata['Pokemon'][pokedata.iloc[:,9].argmin()])

Graveler
Gastly


In [16]:
# creating a subset of fast and non-Fire pokemon
poke_bool = (pokedata.loc[:, 'BaseSpeed'] >= 60) & (pokedata.loc[:, 'MainType']  != 'Fire')
# poke_bool
fast_nofire = pokedata.loc[poke_bool, :]
fast_nofire.head()

Pokemon MainType SecondaryType  Height  Weight  Damage  BaseSpeed  \
Pokedex                                                                         
2           Ivysaur    Grass        Poison      39    28.7      60         60   
3          Venusaur    Grass        Poison      79   220.5      80         80   
9         Blastoise    Water           NaN      63   188.5      79         78   
12       Butterfree      Bug        Flying      43    70.5      60         70   
15         Beedrill      Bug        Poison      39    65.0      65         75   

         Attack  Defense        BMI  
Pokedex                              
2            62       63  13.265023  
3            82       83  24.837606  
9            83      100  33.387629  
12           45       50  26.804489  
15           90       40  30.042735

In [17]:
# using the .describe()
pokedata.describe()

Height       Weight      Damage   BaseSpeed      Attack  \
count  151.000000   151.000000  151.000000  151.000000  151.000000   
mean    46.894040   100.766954   64.218543   68.933775   72.913907   
std     37.880717   131.299070   28.585519   26.746880   26.755421   
min      8.000000     0.200000   10.000000   15.000000    5.000000   
25%     28.000000    21.800000   45.000000   46.500000   51.000000   
50%     39.000000    66.100000   60.000000   70.000000   70.000000   
75%     59.000000   124.250000   80.000000   90.000000   92.000000   
max    346.000000  1014.100000  250.000000  140.000000  134.000000   

          Defense         BMI  
count  151.000000  151.000000  
mean    68.225166   32.764506  
std     26.916704   23.189403  
min      5.000000    0.035425  
25%     50.000000   20.856877  
50%     65.000000   30.042735  
75%     84.000000   38.245600  
max    180.000000  153.707174

The `.describe()` function ran only on the numerical series in the data set; it did not run on the series that were categorical in nature. This means that the `.describe()` function is only used for numerical statistical summaries, and we would need to use something else for the categorical series.