# DS3000 Day 1

Sep 9/10, 2023

Admin
- Modules to install today `pip install collections seaborn numpy pandas` (you may not *need* to do all these, but why not?)
  - If you don't have python and a way to edit jupyter notebooks, now's the time!
- Homework 1 due next Tues, Sep 17 before midnight

Push-Up Tracker
- Section 03: 2
- Section 05: 1

Content
- finish up basic python
- numpy & arrays
- pandas
    - series
    - dataframe

### Question from previous class: Can you call a key from a dictionary based on a value?

Yes! There are a couple ways, but perhaps most simply, make use of `list()`, `.keys()`, `.values()`, and `.index()` and you can do it in one line (could also break this up into parts):

In [1]:
dict_a = {'first': 10, 'second': ["a", "list"], 'third': True}

# for those who may need a second to process the below:
# take the keys of dict_a and make them into a list
# take the values of dict_a and make them into a list
# get the index of the value that corresponds to True
# use square brackets to get the key corresponding to that index
list(dict_a.keys())[list(dict_a.values()).index(True)]

'third'

### Question from previous class: Is there a way to prevent an object from having its type overwritten?

Not easily :(

### Question from previous class: You can initialize an empty list, can you initialize an empty dictionary?

Yes! In fact, let's use it to create an example function to remind ourselves where we left off:

In [2]:
# this module allows you to initialize an empty dictionary
from collections import defaultdict

# another example function
def create_dict(featurenames, features):
    """ creates a dictionary with keys and values corresponding to the inputs

    Args:
        featurenames (list): a list of strings that will serve as the keys to the dictionary
        features (list): a list of values (any type) that will serve as the values of the dictionary

    Returns:
        dict (dictionary): the dictionary
    """

    # create an empty dictionary that will take lists as values
    dict = defaultdict(list)
    
    try:
        for i in range(len(featurenames)):
            # for each feature name, create a key-value pair in the dictionary
            dict[str(featurenames[i])] = features[i]

            # if age is a feature, create a logical column for an age 30 cut-off
            if featurenames[i] == "age":
                dict["old"] = [i > 30 for i in features[i]]
                
    except:
        # if something doesn't work above, let us know
        print("Failure to create dictionary; check inputs")

    return dict

In [3]:
test = ["bloodtype", "age", "height"]
vals = [["A", "B", "AB", "AB+"], [28, 31, 16, 88], [180, 194, 136, 178]]

create_dict(test, vals)

defaultdict(list,
            {'bloodtype': ['A', 'B', 'AB', 'AB+'],
             'age': [28, 31, 16, 88],
             'old': [False, True, False, True],
             'height': [180, 194, 136, 178]})

# LECTURE BREAK/PRACTICE

The Standard Creepiness Rule states that you shouldn't date anyone younger than $\frac{Your Age}{2} + 7$:

![dating](https://imgs.xkcd.com/comics/dating_pools.png)

Spend 5-10 minutes writing a function that takes as input a person's age, and outputs the sentence: `"You can date people at least {result} years old."` Where `{result}` is the result of calculating the lower bound of the SRC.

Then, define a variable `neighbor_age = int(input())` and pass it to your function after your neighbor enters their age.

**note 1**: we are using `int(input())` because by default `input()` takes only strings and we are going to be passing our function an integer. (This will be helpful on Part 2 of the HW!)

**note 2**: the solutions to this are in `Day0_BreakSolution` on Canvas.

## `import`-ing 

We can use software from [Python's standard library](https://docs.python.org/3/library/index.html) or anything on [pypi](https://pypi.org/) (e.g. pandas, numpy, scipy, matplotlib ....this is where folks share their python software) by `import`-ing it into our code. We already imported the math module earlier to be able to use $\pi$ and the collections module to use `defaultdict()`.

(If its on pypi you must install it via pip before use, everything in the standard library comes with Python itself).

Lets build a random number generator:

In [4]:
# imports the whole library
import random

# you can access these functions as attributes of 'random'
random.choices(['pick me', 'or me', 'maybe me?'])

['pick me']

In [5]:
# import just the function you'd like from the library
from random import choices

# importing as immediately above, you may only use the functions you've explicitly imported
choices(['pick me', 'or me', 'maybe me?'])

['maybe me?']

Veteran programming instinct: wondering (and checking) "Does this function also do this other behavior?"

Go to the [official documentation](https://docs.python.org/3/library/random.html) and skim it to see what else you can do with a function.

In [6]:
# we can add a weight parameter which changes how often one item is selected vs another
# if weight of one item is twice the other, it will be picked twice as often
choices(['pick me', 'or me', 'maybe me?'], weights=[1, 2, 3])

['or me']

In [7]:
# or select multiple items by passing k argument
choices(['pick me', 'or me', 'maybe me?'], k=10, weights=[1, 2, 3])

['maybe me?',
 'maybe me?',
 'pick me',
 'or me',
 'maybe me?',
 'maybe me?',
 'maybe me?',
 'pick me',
 'pick me',
 'or me']

# Representing data as arrays (or, matrices, if you prefer, though "array" is more general)
Its often a convenient analogy to consider a dataset as a big table.  A dataset describes the **features** of a collection of **samples**:
- each row represents a sample (or, observation)
    - e.g. a penguin
- each column represents a feature (or, variable)
    - e.g. how heavy the penguins are
- the intersection of a row and column contains the feature of the sample
    - e.g. how heavy a particular penguin is
    
<img src="https://imgur.com/orZWHly.png" width=300 />


In [8]:
# (we'll cover this code later, for now I just want us all to
# look at a dataset together)
import seaborn as sns

# data source = 'https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv'
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

Why represent data in 2d arrays?
- many datasets well encapsulated as a 2d array with 
    - different rows used for samples
    - different col used feature
- Arrays (matrices) are natural math objects in linear algebra, probability and statistics all of which underpin machine learning.

## Rows vs Columns
<img src="https://learnenglishfunway.com/wp-content/uploads/2021/07/Row-vs-Column.jpg" width=700 />

## **NumPy** (**Numerical Python**) Library
* First appeared in 2006 and is the **preferred Python array implementation**.
* High-performance, richly functional **_n_-dimensional array** type called **`ndarray`**. 
* **Written in C** and **up to 100 times faster than lists**.
* Critical in big-data processing, AI applications and much more. 
* According to `libraries.io`, **over 450 Python libraries depend on NumPy**. 
* Many popular data science libraries such as Pandas, SciPy (Scientific Python) and Keras (for deep learning) are built on or depend on NumPy. 

Big Question:
```
What is an array/matrix?  (and how is different than a list or list of lists?)
```

| Array                                 | List (Python: Dynamic Array)                         |
|---------------------------------------|------------------------------------------------------|
| Size is static (contiguous memory)    | Size can be modified quickly (non-contiguous memory) |
| Quick to compute (esp Linear Algebra) | Slower to compute (and clumsy looking code)          |
| contains 1 datatype (numeric)         | may contain many data types (need not be numeric)    |

### Initializing arrays:
- 1d from list / tuple
- 2d from list / tuple

In [9]:
import numpy as np

# x is a 1d array (3)
x = np.array((1, 2, 3))
x

array([1, 2, 3])

In [10]:
# y is a 2d array (2, 3)
y = np.array([[1, 2, 3],
              [4, 5, 6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

### Building some special matrices
- zeros
- ones
- full 
- identity


<img src="https://learnenglishfunway.com/wp-content/uploads/2021/07/Row-vs-Column.jpg" width=200 />

#### Convention: Rows First!
- we describe array shape as `(n_rows, n_cols)`
- we index into an array as `x[row_idx, col_idx]`

In [11]:
# shape = (n_rows, n_cols)
# shape = (height, width)
# .zeros gives an array of all zeros
z = np.zeros((5, 2)) # tall array
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
# .ones gives an array of all ones
one_array = np.ones((2, 5), dtype=int)
one_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# can use .full to create an array of all fill_value
# np.full(shape=(2,5), fill_value=2)
two_array = np.full(shape=(2, 5), fill_value=2.0)
two_array

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [14]:
# identity matrix
# 1's on the diagonal, 0s elsewhere
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arrays which change: 
- `.arange()`
- `.linspace()`
- `.geomspace()`
- `.logspace()`

In [15]:
# note: not "arrange", but rather "(a)rray (range)"
# np.arange(start (inclusive), stop (exclusive), step)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# linearly spaced values np.linspace(start (inclusive), stop (inclusive), size)
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [17]:
# geom spaced values np.geomspace(start (inclusive), stop (inclusive), size)
np.geomspace(1, 27, 4)

array([ 1.,  3.,  9., 27.])

In [18]:
# log spaced value np.logspace(start_exp, stop_exp, size)
# start = 10^start_exp, stop = 10^stop_exp
np.logspace(0, 2, 3)

array([  1.,  10., 100.])

Can you get log spaced values for a base other than 10?

In [19]:
# what about a different base? e-asy!
import math
np.logspace(0, 2, 3, base=math.exp(1))

array([1.        , 2.71828183, 7.3890561 ])

### Array Attributes
- shape
- size
- ndim

Numpy can build arrays out of many different number types (bool, int, float).  ([see also](https://numpy.org/doc/stable/user/basics.types.html#:~:text=There%20are%205%20basic%20numerical,point%20(float)%20and%20complex.&text=NumPy%20knows%20that%20int%20refers,int_%20%2C%20bool%20means%20np.))
- dtype
    - astype
- nbytes

In [20]:
x = np.array([[1, 2, 3],
              [4, 5, 6]]) 

In [21]:
# whether you see int32 or int64 depends on the bit size; it should not truly matter
x.dtype

dtype('int32')

In [22]:
# ndim is the (n)umber of (dim)ensions
x.ndim

2

In [23]:
# shape gives the values of the dimensions
x.shape

(2, 3)

In [24]:
# size is total number of elements
x.size

6

In [25]:
x.nbytes

24

In [26]:
# converting the type of an array can help lower the memory demands
# https://numpy.org/doc/stable/user/basics.types.html
x_low_mem = np.array([[1, 2, 3],
                      [4, 5, 6]], np.uint8)
x_low_mem.nbytes

6

## Manipulating array shape

### Diagonal

The diagonal of each array is shaded below, the unshaded elements are not on the diagonal of the matrix:

$$ \begin{bmatrix}
\blacksquare & \square & \square\\
\square & \blacksquare & \square\\
\square & \square & \blacksquare\\
\square & \square & \square\\
\end{bmatrix} 
\hspace{2cm}
\begin{bmatrix}
\blacksquare & \square & \square & \square & \square\\
\square & \blacksquare & \square& \square & \square\\
\square & \square & \blacksquare& \square & \square\end{bmatrix}
\hspace{2cm}
\begin{bmatrix}
\blacksquare & \square & \square\\
\square & \blacksquare & \square\\
\square & \square & \blacksquare
\end{bmatrix} 
$$

### Numpy methods
- transpose
- `.reshape()`
    - order of reshape (row or column first?)

In [27]:
x = np.array([[1, 2, 3],
              [4, 5, 6]]) 
x

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# transpose (.T): flip across the diagonal
y = x.T
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
# reshape allows us to change shape of matrix by defining the dimensions
x.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [30]:
# (new matrix must have same total number of elements)
# x.reshape((1, 8))

In [146]:
z = np.arange(0, 15)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [147]:
z.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [150]:
# -1 may be used at most once in the shape argument; it is used to tell python to
# choose the value to ensure output array has same number of elements
z.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
# be mindful that -1 can be replaced by some integer to keep same number of elements in array
# but you need to make sure that the multiplication works!
# z.reshape((5, -1))

In [35]:
# we can fill the array across the rows first (order='C'), which is the default
z.reshape((3, 4), order='C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
# or down columns first (order='F')
z.reshape((3, 4), order='F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

## Array Indexing (slicing)

You can index arrays, everything we've previously shown about `start:stop:step` indexing works for arrays too!

In [37]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
x[5]

5

In [39]:
x[2:6]

array([2, 3, 4, 5])

In [40]:
x[-3:]

array([ 8,  9, 10])

In [41]:
x[:5]

array([0, 1, 2, 3, 4])

A two dimensional array requires two indices to get a value: `x[row_idx, col_idx]`

(Just like our convention for rows first in shape, the row index comes first as we index into the array)

In [42]:
x = np.arange(20).reshape((4, 5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
# row_idx=1 (second row since python starts counting at 0)
# col_idx=2 (third row since python starts counting at 0)
x[1, 2]

7

In [44]:
# we can start:stop:step slice either index

# get a slice of rows and a constant column
x[0:2, 2]

array([2, 7])

In [45]:
# get a slice of columns and a constant row
x[2, 0:2]

array([10, 11])

## Super useful slice syntax on arrays:
(so useful it deserves its own title)

In [46]:
# by default, the slice indexing chooses start:stop to give the entire object
x = np.array([1, 2, 3])
x[:]

array([1, 2, 3])

In [47]:
# we can use this to get an entire rows or columns as needed
x = np.arange(20).reshape((4, 5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
# get the first column
x[:, 0]

array([ 0,  5, 10, 15])

In [49]:
# get the second row
x[1, :]

array([5, 6, 7, 8, 9])

In [50]:
# get the last two columns
x[:, -2:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

### Computing stats on an array
- `.sum()`
- `.min()`
- `.max()`
- `.mean()`
- `.std()`
    - standard deviation
- `.var()`
    - variance
- `.argmin()`
    - index of item which is smallest
- `.argmax()`
    - index of item which is largest

In [51]:
x = np.array([4, 3, 5, 4])
x

array([4, 3, 5, 4])

In [52]:
# get index of smallest item
# (smallest item, 3, is at index 1)
x.argmin()

1

In [53]:
y = np.arange(100, 112).reshape((3, 4))
y

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [54]:
y.sum(), y.min(), y.max(), y.mean(), y.std(), y.var()

(1266, 100, 111, 105.5, 3.452052529534663, 11.916666666666666)

In [55]:
# axis: which of the shape parameters should I operate on? 
# shape = (shape0, shape1)

# axis=0 averages across different rows to give the column average
y.mean(axis=0)

array([104., 105., 106., 107.])

In [56]:
# axis=1 averages across different columns to give the row average
y.mean(axis=1)

array([101.5, 105.5, 109.5])

In [57]:
# axis is an accepted keyword of all methods listed above
y.min(axis=1)

array([100, 104, 108])

In [58]:
y.min(axis=0)

array([100, 101, 102, 103])

## Why are we doing this again?

<img src="https://imgur.com/orZWHly.png" width=300 />

In [59]:
import seaborn as sns

# data source = 'https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv'
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

## Array Operations: 
- array and a scalar: 
    - apply operation to every element of array
- array and array: 
    - apply operation to corresponding elements of arrays (requires shape or [special](https://numpy.org/doc/stable/user/basics.broadcasting.html) structure)


In [60]:
y1 = np.arange(12).reshape((3, 4))
y

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [61]:
y1 + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [62]:
y1 * 10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [63]:
y1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [64]:
# array and array arithmetic
y2 = np.arange(100, 112).reshape((3, 4))
y2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [65]:
# array and array arithmetic applies operation to corresponding items in arrays
y1 + y2

array([[100, 102, 104, 106],
       [108, 110, 112, 114],
       [116, 118, 120, 122]])

In [66]:
y1 * y2

array([[   0,  101,  204,  309],
       [ 416,  525,  636,  749],
       [ 864,  981, 1100, 1221]])

In [67]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
# (++) adding a constant row (x) to all rows of a matrix (y1)
# more details here: https://numpy.org/doc/stable/user/basics.broadcasting.html
x = np.array([1000, 2000, 3000, 4000])
y1 + x

array([[1000, 2001, 3002, 4003],
       [1004, 2005, 3006, 4007],
       [1008, 2009, 3010, 4011]])

# If I haven't given it yet, it's 5-minute Break Time! Ask me questions about NumPy, or go get water, or stretch, or just veg out for a few minutes.

# Pandas

Pandas is a python module which stores data.  

### If we already have `np.array()`, why do we need pandas?
- pandas supports non numeric data (strings for categorical data, for example)
- pandas supports reading / storing data from more formats
    - csv (spreadsheets)
- pandas more elegantly deals with missing data
- pandas handles indexing woes

You could do almost everything pandas does with numpy arrays ... but it would be much more difficult to accomplish.

### Pandas has two essential objects:
- **dataframe**
    - 2 dimensional data structure
    - you've already seen one today!  (we replicate below)
- **series (vectors)**
    - 1 dimensional data structure, each item associated with some index
    - you could store the weight of all the penguins as a series 
        - (all samples of one feature)
    - you could store the weight, bill size, sex, island, etc for a single penguin as a series
        - (all features for one sample)

In [69]:
import seaborn as sns

# df stands for dataframe.  df_penguin is a dataframe of penguin data
df_penguin = sns.load_dataset('penguins')
df_penguin.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [70]:
# the table above is a dataframe
type(df_penguin)

pandas.core.frame.DataFrame

## Pandas Series
### building:
- building: default index
- building: custom index
- building: from a dict

In [71]:
# each row, or column is a series object
# this represents first row of dataframe
penguin0_series = df_penguin.iloc[0, :]
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
Name: 0, dtype: object

Pandas series contain a sequence of labelled data elements:
- penguin0's `species` is `Adelie`
- penguin0's `island` is `Torgersen`
- penguin0's `bill_length_mm` is `39.1` ...
- penguin0's `<index-name>` is `<corresponding-value>`

A series is quite similar to a dictionary ...

In [72]:
penguin0_dict = {'species': 'Adelie',
 'island': 'Torgersen',
 'bill_length_mm': 39.1,
 'bill_depth_mm': 18.7,
 'flipper_length_mm': 181.0,
 'body_mass_g': 3750.0,
 'sex': 'Male'}

In [73]:
import pandas as pd

# build a series from dict
penguin0_series = pd.Series(penguin0_dict)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [74]:
# you can also pass two corresponding lists / tuples
index = ['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex']
values = ['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male']

penguin0_series = pd.Series(values, index=index)
penguin0_series

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       Male
dtype: object

In [75]:
# sometimes your data has no meaningful index
# pandas will default to indexing things with integers
ice_cream_flavors = 'vanilla', 'chocolate', 'cherry garcia', 'oatmeal'
pd.Series(ice_cream_flavors)

0          vanilla
1        chocolate
2    cherry garcia
3          oatmeal
dtype: object

In [76]:
# you can access values via .values
penguin0_series.values

array(['Adelie', 'Torgersen', 39.1, 18.7, 181.0, 3750.0, 'Male'],
      dtype=object)

In [77]:
# you can access index via .index
penguin0_series.index

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

### Using Series (hey, don't they look a little like dictionaries?)
- casting dictionaries to series
- accessing custom index:
    - by name: `series.loc[name]`
    - by position: `series.iloc[idx]`
- iterating: keys, items, iteritems (much like dict)
- deleting an entry

In [78]:
dict_fav_num = {'eric':  17, 'qi': 7, 'lynne': 3, 'tamrat': 1}
series_fav_num = pd.Series(dict_fav_num)
series_fav_num

eric      17
qi         7
lynne      3
tamrat     1
dtype: int64

In [79]:
# lookup value associated with index='eric'
series_fav_num['eric']

17

In [80]:
# another way to lookup value associated with index='eric'
series_fav_num.loc['eric']

17

In [81]:
# return the value in position 2 (the third position, from top)
series_fav_num.iloc[1]

7

In [82]:
# each of these access methods can also set the value
series_fav_num.iloc[2] = 1000
series_fav_num

eric        17
qi           7
lynne     1000
tamrat       1
dtype: int64

In [83]:
for idx in series_fav_num.index:
    print(idx)

eric
qi
lynne
tamrat


In [84]:
# check membership of item in index
'eric' in series_fav_num.index

True

In [85]:
'alice' in series_fav_num.index

False

In [86]:
# iterating through values
for val in series_fav_num.values:
    print(val)

17
7
1000
1


In [87]:
# iterating through index (just a like dict!)
# .keys() produces same thing as .index
for key in series_fav_num.keys():
    print(key)

eric
qi
lynne
tamrat


In [88]:
# iterating through index, value pairs (just like dict!)
for key, val in series_fav_num.items():
    print(key, val)

eric 17
qi 7
lynne 1000
tamrat 1


In [89]:
# removing a pair by its corresponding index (just like dict!)
del series_fav_num['eric']

In [90]:
series_fav_num

qi           7
lynne     1000
tamrat       1
dtype: int64

### Describing a `pd.Series`

Just like numpy arrays:
- `Series.argmin()`
    - which index has smallest value
    - pandas gives the row number, not the index
- `Series.argmax()`
    - which index has largest value
    - pandas gives the row number, not the index
- `Series.mean()`
- `Series.min()`
- `Series.max()`
- `Series.std()`
- `Series.var()`

New to pandas:
- `Series.count()`
    - number of item pairs in series
- `Series.describe()`
    - summary statistics

In [91]:
# number of entries (rows)
series_fav_num.count()

3

In [92]:
# other descriptors/summary statistics
series_fav_num.describe()

count       3.000000
mean      336.000000
std       575.048694
min         1.000000
25%         4.000000
50%         7.000000
75%       503.500000
max      1000.000000
dtype: float64

## Pandas: DataFrame

Remember:
- `Series`:  1d data object
- `DataFrame`: 2d data object

`DataFrame`s represent two-dimensional data, for example, grades:

|           | Quiz 0 | Quiz 1 | Quiz 2 |
|-----------|--------|--------|--------|
| Student 0 | 80     | 90     | 50     |
| Student 1 | 87     | 92     | 80     |

Each column or row above could be considered a `Series` object (as we'll see later, we can indeed extract a single row or column of a dataframe as a `Series` object).

In [93]:
import pandas as pd
import numpy as np

quiz_array = np.array([[80, 90, 50],
                 [87, 92, 80]])

df_quiz = pd.DataFrame(quiz_array, 
                       columns=('quiz0', 'quiz1', 'quiz2'), 
                       index=('student0', 'student1'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [94]:
# we construct a dataframe as a dictionary
# keys of the dictionary are columns of dataframe
# values are lists (or tuples) of the values in each column
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
pd.DataFrame(quiz_dict, index=('student0', 'student1'))

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [95]:
# another way to construct, this time the transpose
quiz_dict2 = {'student0': [80, 90, 50],
             'student1': [87, 92, 80]}
pd.DataFrame(quiz_dict2, index=('quiz0', 'quiz1', 'quiz2'))

student0  student1
quiz0        80        87
quiz1        90        92
quiz2        50        80

In [96]:
# could also use .transpose() or even .T
df_quiz.transpose()
# df_quiz.T

student0  student1
quiz0        80        87
quiz1        90        92
quiz2        50        80

In [97]:
# we can also add the column or index names after creation
df_quiz = pd.DataFrame(quiz_array)
df_quiz

0   1   2
0  80  90  50
1  87  92  80

In [98]:
df_quiz.columns = ['quiz0', 'quiz1', 'quiz2']
df_quiz.index = ('student0', 'student1')
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

### Describing a `pd.DataFrame`

Similar to Series (for now), but with a couple differences:
- `DataFrame.iloc[].idxmin()` or `DataFrame.loc[].idxmin()` 
    - note that this does not work on the DataFrame itself, but on specified series/rows
    - which index has smallest value
    - pandas gives the row number, not the index
- `DataFrame.iloc[].idxmax()` or `DataFrame.loc[].idxmax()`
    - note that this does not work on the DataFrame itself, but on specified series/rows
    - which index has largest value
    - pandas gives the row number, not the index
- `DataFrame.mean()`
- `DataFrame.min()`
- `DataFrame.max()`
- `DataFrame.std()`
- `DataFrame.var()`

New to pandas:
- `DataFrame.count()`
    - number of item pairs in series
- `DataFrame.describe()`
    - summary statistics

In [99]:
# by default, each method applies operation to entire column of data
# note that there may be some complaining from python if not all the columns are numeric
df_quiz.mean()

quiz0    83.5
quiz1    91.0
quiz2    65.0
dtype: float64

In [100]:
# we can also pass axis parameter to specify if operation should be applied to row or column
# !remember!
# axis=0 -> apply operation across all rows (returns operation per col)
# axis=1 -> apply operation across all cols (returns operation per row)
df_quiz.mean(axis=1)

student0    73.333333
student1    86.333333
dtype: float64

In [101]:
# describe only works on columns
df_quiz.describe()

quiz0      quiz1      quiz2
count   2.000000   2.000000   2.000000
mean   83.500000  91.000000  65.000000
std     4.949747   1.414214  21.213203
min    80.000000  90.000000  50.000000
25%    81.750000  90.500000  57.500000
50%    83.500000  91.000000  65.000000
75%    85.250000  91.500000  72.500000
max    87.000000  92.000000  80.000000

## Indexing / Accessing a DataFrame
- indexing: 
    - `.loc[]` indexing by name of row or column
    - `.iloc[]` indexing by position integer (0, 1, 2, 3, 4 ...)
    & slicing & subsets
- using `:` to get full rows or columns
- single cell's contents: `at`, `iat` & slicing

In [102]:
# indexing data by "name"
# remember: rows first, then columns ... 
# 1st entry describes which row ('student0')
# 2nd entry describes which col ('quiz0')

df_quiz.loc['student0', 'quiz0']

80

In [103]:
# index data by position
# 1st entry describes which row.  0 -> the 1st (topmost) row
# 2nd entry describes which col.  2 -> the 3rd (from the left) col
df_quiz.iloc[0, 2]

50

In [104]:
# you can use same slicing syntaxes on both .loc and .iloc
# 1st row, last col
df_quiz.iloc[0, -1]

50

In [105]:
# all rows, only the second col
df_quiz.iloc[:, 1]

student0    90
student1    92
Name: quiz1, dtype: int32

In [106]:
# all rows, only quiz0
df_quiz.loc[:, 'quiz0']

student0    80
student1    87
Name: quiz0, dtype: int32

In [107]:
# slicing with named cols and rows
# you can get a range, by name of row/col
# note: this includes both start and stop columns
df_quiz.loc['student0', 'quiz0':'quiz2' ]

quiz0    80
quiz1    90
quiz2    50
Name: student0, dtype: int32

In [108]:
# watch out:
# when you get ranges indexed by position: include start idx, exclude stop idx)
df_quiz.iloc[0, 0:2 ]

quiz0    80
quiz1    90
Name: student0, dtype: int32

In [109]:
# if you access directly into dataframe, it will assume you're looking for a column
# (below is equivilent to df_quiz.loc[:, 'quiz0'])
df_quiz['quiz0']

student0    80
student1    87
Name: quiz0, dtype: int32

## Modifying a DataFrame
- updating values: single cell
- adding a new column
- `pd.DataFrame.append()` and `pd.DataFrame.concat()`
    - adds a single row to a dataframe
    - `.append()` is deprecated, and may not work depending on your version of Python! Has been replaced with `.concat()` (which we use here)

In [110]:
# setting single entry in dataframe
df_quiz.loc['student0', 'quiz1'] = 123
df_quiz

quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [111]:
# adding a new column (which student got which grade?)
# notice data frames can include columns of multiple types!
df_quiz['overall grade'] = 'a', 'b' 
df_quiz

quiz0  quiz1  quiz2 overall grade
student0     80    123     50             a
student1     87     92     80             b

In [112]:
# delete a column
del df_quiz['overall grade']
df_quiz

quiz0  quiz1  quiz2
student0     80    123     50
student1     87     92     80

In [113]:
# adding a column (next 2 cells) more error robust way of handling indexing
# by explicitly labelling the index we're sure to match more explicitly
s_overgrade = pd.Series({'student1': 'b-',
                         #'student0': 'a+',
                        'student2': 'f (no quizzes taken)'})
s_overgrade

student1                      b-
student2    f (no quizzes taken)
dtype: object

In [114]:
# notice how pandas helps us out in aligning our new column with proper row
# (and avoids including student2)
df_quiz['overall grade'] = s_overgrade
df_quiz

quiz0  quiz1  quiz2 overall grade
student0     80    123     50           NaN
student1     87     92     80            b-

In [115]:
# how to 'drop' a row (returns a dataframe with row removed)
df_quiz_short = df_quiz.drop('student0')
df_quiz_short

quiz0  quiz1  quiz2 overall grade
student1     87     92     80            b-

In [116]:
# rebuild df_quiz
quiz_dict = {'quiz0': [80, 87],
            'quiz1': [90, 92],
            'quiz2': [50, 80]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [117]:
# notice: name of series ends up on index of dataframe
# notice: order of items in series doesnt matter, they're aligned by index
s_student3 = pd.Series({'quiz1': 90,
                        'quiz2': 100,
                        'quiz0': 95},
                      name='student3')
s_student3

quiz1     90
quiz2    100
quiz0     95
Name: student3, dtype: int64

In [118]:
# add new row to dataframe
pd.concat([df_quiz, s_student3.to_frame().T])

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student3     95     90    100

In [119]:
# also notice: .concat() returns a copy of df_quiz, it isn't modified above
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80

In [120]:
# thus, must overwrite:
df_quiz = pd.concat([df_quiz, s_student3.to_frame().T])
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student3     95     90    100

In [121]:
# adding a column that is a function of other columns:
df_quiz['average'] = (df_quiz['quiz0'] + df_quiz.quiz1 + df_quiz.quiz2)/3
df_quiz

quiz0  quiz1  quiz2    average
student0     80     90     50  73.333333
student1     87     92     80  86.333333
student3     95     90    100  95.000000

In [122]:
df_quiz.average

student0    73.333333
student1    86.333333
student3    95.000000
Name: average, dtype: float64

In [123]:
df_quiz['quiz0']

student0    80
student1    87
student3    95
Name: quiz0, dtype: int64

### Operating on DataFrame & Series Objects

Your operators do what you'd expect them to:

In [124]:
df_quiz * 1000

quiz0  quiz1   quiz2       average
student0  80000  90000   50000  73333.333333
student1  87000  92000   80000  86333.333333
student3  95000  90000  100000  95000.000000

In [125]:
# we can also use comparison operators (super helpful, see boolean indexing next)
df_quiz >= 85

quiz0  quiz1  quiz2  average
student0  False   True  False    False
student1   True   True  False     True
student3   True   True   True     True

### Boolean Indexing into DataFrame

Sometimes we want to grab only the rows or columns which meet a particular condition.

"Get all students whose grade was higher than 85 on quiz 1"

In [126]:
quiz_dict = {'quiz0': [80, 87, 60, 30],
            'quiz1': [90, 92, 60, 23],
            'quiz2': [50, 80, 70, 64]}
df_quiz = pd.DataFrame(quiz_dict, index=('student0', 'student1', 'student2', 'student3'))
df_quiz

quiz0  quiz1  quiz2
student0     80     90     50
student1     87     92     80
student2     60     60     70
student3     30     23     64

In [127]:
# quiz 2 is a series object which contains every index's quiz 2 grade
# one, verbose way:
s_quiz2 = df_quiz.loc[:, 'quiz2']
s_quiz2

student0    50
student1    80
student2    70
student3    64
Name: quiz2, dtype: int64

In [128]:
# easier way, but not as convenient for seeing what we're about to do
df_quiz.quiz2

student0    50
student1    80
student2    70
student3    64
Name: quiz2, dtype: int64

In [129]:
# boolean indexing: using a boolean series as index returns only those entries which are True
# notice that since student2 & student3's quiz1 grade wasn't > 80 they aren't included below
df_quiz.loc[s_quiz2 >= 70, :]

quiz0  quiz1  quiz2
student1     87     92     80
student2     60     60     70

In [130]:
# we can build more complex conditions using 
# & (and operator)
# | (or operator)

# all students who got at least an 80 on quiz1 but scored less than 75 on quiz2
s_bool = (df_quiz.loc[:, 'quiz1'] >= 80) & (df_quiz.quiz2  < 75)
s_bool

student0     True
student1    False
student2    False
student3    False
dtype: bool

In [131]:
df_quiz.loc[s_bool, :]

quiz0  quiz1  quiz2
student0     80     90     50

# Loading Data into Pandas

Data comes from many places:
- Web Scraping
- Application Program Interface (API)
- SQL
- local file:
    - csv
    - JSON
    - fixed width tables (HTML)
    
### Pandas functions which load data
| Mode | Description
| ------ | :------
| **`read_csv`** | Load comma seperated values data from a file or URL (other delimeters too!)
| **`read_xlsx`** | Read data in xls format (Mircosoft Excel)
| **`read-fwf`** | Read data in fixed-width column format (i.e., no delimiters such as tab-separated txt files)
| **`read_clipboard`** | Version of read_csv that reads data from the clipboard; useful for converting tables from web pages
| **`read_html`** | Read all tables contained in the given HTML document.
| **`read_json`** | Read data from a JSON (JavaScript Object Notation) string representation

## Reading CSV into Pandas
- read_csv
- index_col
- header

In [132]:
# note: file must be in same folder as jupyter notebook
pd.read_csv('cleaner_gtky.csv')

fake_student_id      time_stamp      class                cs_ds co_op  \
0               1460   9/4/2024 0:17  Sophomore  CS (incl. combined)    No   
1               1091   9/4/2024 7:51  Sophomore  DS (incl. combined)    No   
2               1764  9/4/2024 11:29     Junior  CS (incl. combined)   Yes   
3               1464  9/4/2024 13:23  Sophomore  CS (incl. combined)    No   
4               1629  9/4/2024 14:17  Sophomore  DS (incl. combined)    No   
..               ...             ...        ...                  ...   ...   
138             1275   9/6/2024 2:04  Sophomore  CS (incl. combined)    No   
139             1526  9/6/2024 10:38  Sophomore  DS (incl. combined)    No   
140             1090  9/6/2024 12:43  Sophomore  DS (incl. combined)    No   
141             1591  9/6/2024 13:45  Sophomore  DS (incl. combined)    No   
142             1710  9/6/2024 22:51     Junior  CS (incl. combined)    No   

     python_exp                                       dream_career  \
0             3                                Computer Programmer   
1             1  Data Scientist, Investment Banker, Private Equ...   
2             1                                                NaN   
3             3                  Tech Entrepreneurship or Research   
4             3                     Not sure yet, still exploring.   
..          ...                                                ...   
138           3  Tech consulting, software developer, I'm also ...   
139           3                                  Marketing Analyst   
140           1                                           not sure   
141           2                                    Project Manager   
142           4                       Make some cool games or apps   

                                               hobby  \
0                    I enjoy playing golf and djing.   
1    Exercising (Walking, Bouldering, Weightlifting)   
2                    Cooking and listening to music!   
3                                             Soccer   
4                                      Video Editing   
..                                               ...   
138                         I like writing articles.   
139                                          Dancing   
140                            any outdoor activity    
141                                          running   
142            Stay home with my cats and do nothing   

                                                  song  \
0    https://open.spotify.com/track/2dshtwEGNpyrE0x...   
1    Currently, Halo - Beyonce, https://open.spotif...   
2    https://open.spotify.com/track/42sqQTi2EqDPd6I...   
3                   Stairway to Heaven by Led Zeppelin   
4    ocd - eriddoa (https://open.spotify.com/track/...   
..                                                 ...   
138  The Black Dog - https://open.spotify.com/track...   
139  https://open.spotify.com/track/51rfRCiUSvxXlCS...   
140  https://open.spotify.com/track/1HNkqx9Ahdgi1Ix...   
141  Ode to a Conversation Stuck in Your Throat htt...   
142  https://open.spotify.com/track/2N61DUSk4oIZdrS...   

                                              ai_feels  age_months  pets  \
0    I think it's the future, and the future looks ...       237.0   2.0   
1          I'm a bit worried it might be used for ill.       230.0   1.0   
2          I'm a bit worried it might be used for ill.       244.0   3.0   
3                        It's going to destroy us all!       238.0   0.0   
4    I think it's the future, and the future looks ...       232.0   1.0   
..                                                 ...         ...   ...   
138  It will be useful, but it won't change the wor...       238.0   0.0   
139  It will be useful, but it won't change the wor...       232.0   1.0   
140  I think it's the future, and the future looks ...       232.0   0.0   
141  I think it's the future, and the future looks ...       230.0   1.0   
142  I think it's the

In [133]:
# how to specify index col (make sure this is uniquely identifiable!)
pd.read_csv('cleaner_gtky.csv', index_col='fake_student_id')

time_stamp      class                cs_ds co_op  \
fake_student_id                                                         
1460              9/4/2024 0:17  Sophomore  CS (incl. combined)    No   
1091              9/4/2024 7:51  Sophomore  DS (incl. combined)    No   
1764             9/4/2024 11:29     Junior  CS (incl. combined)   Yes   
1464             9/4/2024 13:23  Sophomore  CS (incl. combined)    No   
1629             9/4/2024 14:17  Sophomore  DS (incl. combined)    No   
...                         ...        ...                  ...   ...   
1275              9/6/2024 2:04  Sophomore  CS (incl. combined)    No   
1526             9/6/2024 10:38  Sophomore  DS (incl. combined)    No   
1090             9/6/2024 12:43  Sophomore  DS (incl. combined)    No   
1591             9/6/2024 13:45  Sophomore  DS (incl. combined)    No   
1710             9/6/2024 22:51     Junior  CS (incl. combined)    No   

                 python_exp  \
fake_student_id               
1460                      3   
1091                      1   
1764                      1   
1464                      3   
1629                      3   
...                     ...   
1275                      3   
1526                      3   
1090                      1   
1591                      2   
1710                      4   

                                                      dream_career  \
fake_student_id                                                      
1460                                           Computer Programmer   
1091             Data Scientist, Investment Banker, Private Equ...   
1764                                                           NaN   
1464                             Tech Entrepreneurship or Research   
1629                                Not sure yet, still exploring.   
...                                                            ...   
1275             Tech consulting, software developer, I'm also ...   
1526                                             Marketing Analyst   
1090                                                      not sure   
1591                                               Project Manager   
1710                                  Make some cool games or apps   

                                                           hobby  \
fake_student_id                                                    
1460                             I enjoy playing golf and djing.   
1091             Exercising (Walking, Bouldering, Weightlifting)   
1764                             Cooking and listening to music!   
1464                                                      Soccer   
1629                                               Video Editing   
...                                                          ...   
1275                                    I like writing articles.   
1526                                                     Dancing   
1090                                       any outdoor activity    
1591                                                     running   
1710                       Stay home with my cats and do nothing   

                                                              song  \
fake_student_id                                                      
1460             https://open.spotify.com/track/2dshtwEGNpyrE0x...   
1091             Currently, Halo - Beyonce, https://open.spotif...   
1764             https://open.spotify.com/track/42sqQTi2EqDPd6I...   
1464                            Stairway to Heaven by Led Zeppelin   
1629             ocd - eriddoa (https://open.spotify.com/track/...   
...                                                            ...   
1275             The Black Dog - https://open.spotify.com/track...   
1526             https://open.spotify.com/track/51rfRCiUSvxXlCS...   
1090             https://open.spotify.com/track/1HNkqx9Ahdgi1Ix...   
1591             Ode to a Conversation Stuck in Your Throat htt...   
1710             https://open.s

In [134]:
# look at the first few rows (header)
gtky = pd.read_csv('cleaner_gtky.csv', index_col='fake_student_id')
gtky.head()

time_stamp      class                cs_ds co_op  \
fake_student_id                                                         
1460              9/4/2024 0:17  Sophomore  CS (incl. combined)    No   
1091              9/4/2024 7:51  Sophomore  DS (incl. combined)    No   
1764             9/4/2024 11:29     Junior  CS (incl. combined)   Yes   
1464             9/4/2024 13:23  Sophomore  CS (incl. combined)    No   
1629             9/4/2024 14:17  Sophomore  DS (incl. combined)    No   

                 python_exp  \
fake_student_id               
1460                      3   
1091                      1   
1764                      1   
1464                      3   
1629                      3   

                                                      dream_career  \
fake_student_id                                                      
1460                                           Computer Programmer   
1091             Data Scientist, Investment Banker, Private Equ...   
1764                                                           NaN   
1464                             Tech Entrepreneurship or Research   
1629                                Not sure yet, still exploring.   

                                                           hobby  \
fake_student_id                                                    
1460                             I enjoy playing golf and djing.   
1091             Exercising (Walking, Bouldering, Weightlifting)   
1764                             Cooking and listening to music!   
1464                                                      Soccer   
1629                                               Video Editing   

                                                              song  \
fake_student_id                                                      
1460             https://open.spotify.com/track/2dshtwEGNpyrE0x...   
1091             Currently, Halo - Beyonce, https://open.spotif...   
1764             https://open.spotify.com/track/42sqQTi2EqDPd6I...   
1464                            Stairway to Heaven by Led Zeppelin   
1629             ocd - eriddoa (https://open.spotify.com/track/...   

                                                          ai_feels  \
fake_student_id                                                      
1460             I think it's the future, and the future looks ...   
1091                   I'm a bit worried it might be used for ill.   
1764                   I'm a bit worried it might be used for ill.   
1464                                 It's going to destroy us all!   
1629             I think it's the future, and the future looks ...   

                 age_months  pets  credit_hours  work_hours  
fake_student_id                                              
1460                  237.0   2.0          18.0         0.0  
1091                  230.0   1.0          17.0        14.0  
1764                  244.0   3.0          17.0         0.0  
1464                  238.0   0.0          18.0         0.0  
1629                  232.0   1.0          16.0         0.0

In [135]:
# or the last few (tail)
gtky.tail()

time_stamp      class                cs_ds co_op  \
fake_student_id                                                         
1275              9/6/2024 2:04  Sophomore  CS (incl. combined)    No   
1526             9/6/2024 10:38  Sophomore  DS (incl. combined)    No   
1090             9/6/2024 12:43  Sophomore  DS (incl. combined)    No   
1591             9/6/2024 13:45  Sophomore  DS (incl. combined)    No   
1710             9/6/2024 22:51     Junior  CS (incl. combined)    No   

                 python_exp  \
fake_student_id               
1275                      3   
1526                      3   
1090                      1   
1591                      2   
1710                      4   

                                                      dream_career  \
fake_student_id                                                      
1275             Tech consulting, software developer, I'm also ...   
1526                                             Marketing Analyst   
1090                                                      not sure   
1591                                               Project Manager   
1710                                  Make some cool games or apps   

                                                 hobby  \
fake_student_id                                          
1275                          I like writing articles.   
1526                                           Dancing   
1090                             any outdoor activity    
1591                                           running   
1710             Stay home with my cats and do nothing   

                                                              song  \
fake_student_id                                                      
1275             The Black Dog - https://open.spotify.com/track...   
1526             https://open.spotify.com/track/51rfRCiUSvxXlCS...   
1090             https://open.spotify.com/track/1HNkqx9Ahdgi1Ix...   
1591             Ode to a Conversation Stuck in Your Throat htt...   
1710             https://open.spotify.com/track/2N61DUSk4oIZdrS...   

                                                          ai_feels  \
fake_student_id                                                      
1275             It will be useful, but it won't change the wor...   
1526             It will be useful, but it won't change the wor...   
1090             I think it's the future, and the future looks ...   
1591             I think it's the future, and the future looks ...   
1710             I think it's the future, and the future looks ...   

                 age_months  pets  credit_hours  work_hours  
fake_student_id                                              
1275                  238.0   0.0          18.0         0.0  
1526                  232.0   1.0          16.0        15.0  
1090                  232.0   0.0          18.0         NaN  
1591                  230.0   1.0          17.0        10.0  
1710                    NaN   NaN          16.0         NaN

In [136]:
# look at stats for the different classes
class_gtky = gtky.groupby("class")
class_gtky.describe()

python_exp                                                 \
               count      mean       std  min   25%  50%   75%  max   
class                                                                 
5th year         2.0  2.500000  0.707107  2.0  2.25  2.5  2.75  3.0   
Faculty          1.0  5.000000       NaN  5.0  5.00  5.0  5.00  5.0   
Freshman         1.0  5.000000       NaN  5.0  5.00  5.0  5.00  5.0   
Junior          33.0  2.909091  0.947485  1.0  2.00  3.0  4.00  4.0   
Senior          18.0  3.277778  1.017815  1.0  3.00  3.0  4.00  5.0   
Sophomore       88.0  2.750000  1.116748  1.0  2.00  3.0  3.00  5.0   

          age_months              ... credit_hours       work_hours            \
               count        mean  ...          75%   max      count      mean   
class                             ...                                           
5th year         2.0  279.500000  ...         16.0  16.0        2.0  3.500000   
Faculty          1.0  374.000000  ...         12.0  12.0        1.0  0.000000   
Freshman         1.0  226.000000  ...         18.0  18.0        1.0  0.000000   
Junior          31.0  240.645161  ...         17.0  20.0       31.0  2.258065   
Senior          18.0  259.000000  ...         16.0  19.0       18.0  7.916667   
Sophomore       88.0  231.672727  ...         18.0  22.0       86.0  4.348837   

                                                  
                std  min   25%  50%    75%   max  
class                                             
5th year   4.949747  0.0  1.75  3.5   5.25   7.0  
Faculty         NaN  0.0  0.00  0.0   0.00   0.0  
Freshman        NaN  0.0  0.00  0.0   0.00   0.0  
Junior     5.561581  0.0  0.00  0.0   0.00  25.0  
Senior     7.452299  0.0  0.00  9.0  12.00  20.0  
Sophomore  6.613298  0.0  0.00  0.0   9.75  20.0  

[6 rows x 40 columns]

## Saving a DataFrame as a csv
- .to_csv()
- index=False
- header=False
- appending to csv (mode='a', header=None)

In [137]:
# doesn't save index into first column of csv
gtky.to_csv('gtky_copy.csv', index=False)

In [138]:
# doesn't save header into first row of csv
gtky.to_csv('gtky_copy_no_head.csv', header=False)

In [139]:
# why would you want to not save the header?
# you could append to an existing csv with mode = 'a'

gtky.to_csv('gtky_copy2.csv', index=False)
for _ in range(10):
    gtky.to_csv('gtky_copy2.csv', header=False, mode='a')

## What's next?

The example above seems a bit contrived, but imagine you have a web-scraping job which goes to some web page every hour and scrapes it to get some new data.  You could just add the new data as a few new rows to your existing dataset with the syntax shown above.

Next Topics (for Homework 2):
- Getting Data from the internet (APIs and Web Scraping)
- Cleaning Data
- Summarizing data with numerical summaries and plots